#!/bin/bash

 echo "Valid Requests:"
 echo "$ create_database database = create a database called \"database\""
 echo "$ create_table database table columns = create a table called \"table\" in database \"database\" with column names \"columns\""
 echo "$ insert database table data = append a row of data at the end of the specified table in the specified database"
 echo "$ select database table columns = select columns by number from the specified table in the specified database"
 echo "$ select_all database table = select all rows in a table"
 echo "$ select_by_name database table columns = same as select, except instead of providing column numbers, provide column names"
 echo "$ select_where database table columns column_number value = same as select, except you only select rows where column_number = value"
 echo "$ select_by_name_where database table columns column_name value = same as select_by_name, except you only select rows where column_name = value"
 echo "$ select_by_name_ordered database table columns column_name = same as select_by_name, except results are sorted by column_name"
 echo "$ insert_no_repeats database table data = same as insert, except a row cannot be entered if the exact same row already exists in the table"
 echo "$ remove_database database = delete entire database"
 echo "$ remove_table database table = delete entire table"
 echo "$ remove_row database table row = removes the row corresponding to \"row\" in the specified table"
 echo "$ remove_row_where database table column_name value = removes all rows in the table where column_name = value"
 echo "$ edit_row database table row replacement = Replace a row with a new row"
 echo "$ column_names database table = Find the column names in a table"
 echo "$ show_databases = show all current databases"
 echo "$ show_tables database = show all tables in a given database"
 echo "$ show_options = show this menu"
 echo "$ shutdown = shutdown server"
 echo "$ exit = exit the server. Can also press ctrl+c to exit"
